language: bash

sudo: required

services:
  - docker

notifications:
  email:
    recipients:
      - travis@23-5.eu
    on_success: always
    on_failure: always

script: 
  - git clone https://github.com/Antikeimena/Sisyphus.git
  - mkdir Glaucus
  - cp -r Main Glaucus  
  - ls -al
  - docker run -v ${PWD}:/host ansi/antikeimenabuildenv build.sh 
  - ls -al
